refactoring: add redux to counter
tigerscave/sono-redux-counter pull request #1
Opened 2018-08-01 03:35 UTC by sonokou1109

2018-08-01 03:36 UTC, sonokou1109 commented
@cdra0624 @zigen

2018-08-01 05:05 UTC, zigen requested changes

2018-08-01 05:05 UTC, zigen commented on src/reducers/reducer.js
> +      const { count } = state;
this `count` is not needed.

2018-08-01 05:05 UTC, zigen commented on src/reducers/reducer.js
> +  console.log(state);
remove `console.log` , since you use redux devtool.

2018-08-01 05:05 UTC, zigen commented on src/reducers/reducer.js
> +    case 'COUNT_UP': {
use `actionType.COUNT_UP`, don't use string literal

2018-08-01 05:05 UTC, zigen commented on src/reducers/index.js
> +  count: reducer,
the name `reducer` is not good. `count` or ` counter` is better.
you should change the file name `reducer.js` to `counter.js`

2018-08-01 05:05 UTC, zigen commented on src/components/App.js
> +  console.log(state);
remove `console.log`

2018-08-01 05:05 UTC, zigen commented on src/components/App.js
> +    const { count } = this.props;
also assign `countUp`, `countDown`, `countReset` here.

2018-08-01 05:05 UTC, zigen commented on src/components/App.js
> +/*  constructor(props) {
do not comment out previous code.
why do you use git????

2018-08-01 05:05 UTC, zigen commented on src/actions/countAction.js
> +  return dispatch => {
no need to return function which takes `dispatch`.
this function should return action object

2018-08-02 14:39 UTC, closed without merging

2018-08-02 14:39 UTC, sonokou1109 commented
I close this PR

2018-08-02 14:40 UTC, sonokou1109 commented
This feature moves to #2